/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../editor/src/**/*.{js,ts,jsx,tsx}'
  ],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: "transparent",
      black: "#000000",
      white: "#FFFFFF",
      "fb-color": "#1877F2",
      gray: {
        1: '#F9F9FB',
        2: '#F3F3F6',
        3: '#EDEFF2',
        4: '#CDD1DA',
        5: '#ACB2C2',
        6: '#78829C',
        7: '#383B44',
        8: '#3C3C3C',
        9: '#414141',
        10: '#6F7495',
        11: '#DADCE6',
        12: '#F6F6F6',
        13: '#747775',
        14: '#1F1F1F',
        15: '#363636',
        16: '#ADB2C1',
        17: '#5E5E5E',
        18: '#839299',
        19: '#E5E5E5',
        20: '#FBFBFB',
        21: '#1c1c1c',
        22: '#EEEFF1',
        23: '#F1F1F1',
        24: '#5C5E63',
        25: '#CFD0D2',
        26: '#605E5C',
        27: '#E6E7EA',
        28: '#6E6E6E',
        29: '#666666',
        30: '#EDEDED',
        31: '#4D4D4D',
        32: '#3D3D3D',
        33: '#FAFAFA',
        34: '#75777C',
        35: '#C7C7CC',
        36: '#8E8E93',
        37: '#F3F3F3',
        38: '#F4F5F6',
        39: '#8C90AA',
        40: '#FFFFFF80',
        41: '#FFFFFF1F',
        42: '#AEAEB2',
        43: '#48484A',
        44: '#F2F2F7',
        44.5: '#F2F2F733',
        45: '#D1D1D6',
        46: '#E5E5EA',
        47: '#393B44',
        48: '#2c2c2e',
        49: '#636366',
        50: '#EBEBEB',
        51: '#262626',
        52: '#F4F4F5',
        53: '#475467',
        54: '#707070',
      },
      red: {
        1: "#FDF1F4",
        2: "#FAE0E8",
        3: "#ED1C57",
        4: "#D01147",
        5: "#D01047",
      },
      green: {
        1: "#8ACC1A",
        2: "#2CD162",
        3: "#26A871",
        4: "#008060",
        5: "#E5EED9",
        6: '#D5FFAB',
        7: '#C4F5C4',
        8: '#E8F8EC',
        9: '#E9FCC3',
      },
      blue: {
        1: "#EBF3FF",
        2: "#0DD3FF",
        3: "#01C4CB",
        4: "#307EF3",
        5: "#0743DC",
        6: "#9AE1E4",
        7: "#C8F9FE",
        8: "#1873F2",
      },
      purple: {
        1: "#F8F6FE",
        2: "#F4F1FE",
        3: "#E5DEFC",
        4: "#DED5FB",
        5: "#5536DB",
        6: "#4C2BD9",
        7: "#4022BE",
        8: "#5436DB",
        9: '#F0E6FF',
        10: '#7B6AC4',
        11: '#F6F2FF',
        12: '#9162F9',
        13: '#D7C7FB',
        14: '#403C4D',
        15: '#BFB4F1',
        16: '#2F2C39',
        17: '#3A3649'
      },
      yellow: {
        1: "#FFB803",
        2: "#FE9B08",
        2.5: "#FF7A0B",
        3: "#FF640D",
        4: "#FB3C3C",
        5: '#FFEAB3',
        6: '#FEF3E1',
        7: '#FFFBAD',
      },
      pink: {
        1: "#F05DC7",
        2: "#A539F9",
        3: "#D63384",
        4: "#FD9BD0",
      },
      dark: {
        1: "#0E0E0E",
        1.5: "#151515",
        2: "#171717",
        3: "#1C1C1C",
        4: "#1D1D1D",
        5: "#121212",
        6: "#1A191A",
        7: "#2B2F3B",
        8: "#131314",
        9: "#303030",
        10: "#232529",
        11: "#121212",
        12: "#101010",
        13: "#3A3A3C",
        14: "#1C1C1E",
        15: '#191915',
      },
      indigo: {
        1: '#95A4FC'
      },
      primary: {
        dark: 'var(--primary-dark)',
        light: 'var(--primary-light)',
      },
      button: {
        primary: {
          'default-bg': 'var(--button-primary-default-bg)',
          'default-text': 'var(--button-primary-default-text)',
          'hover-bg': 'var(--button-primary-hover-bg)',
          'hover-text': 'var(--button-primary-hover-text)',
          'loading-bg': 'var(--button-primary-loading-bg)',
          'loading-text': 'var(--button-primary-loading-text)',
          'disabled-bg': 'var(--button-primary-disabled-bg)',
          'disabled-text': 'var(--button-primary-disabled-text)',
          'icon': 'var(--button-primary-icon-default)',
        },
        secondary: {
          'default-bg': 'var(--button-secondary-default-bg)',
          'default-stroke': 'var(--button-secondary-default-stroke)',
          'default-text': 'var(--button-secondary-default-text)',
          'hover-bg': 'var(--button-secondary-hover-bg)',
          'hover-stroke': 'var(--button-secondary-hover-stroke)',
          'hover-text': 'var(--button-secondary-hover-text)',
          'loading-bg': 'var(--button-secondary-loading-bg)',
          'loading-stroke': 'var(--button-secondary-loading-stroke)',
          'loading-text': 'var(--button-secondary-loading-text)',
          'disabled-bg': 'var(--button-secondary-disabled-bg)',
          'disabled-stroke': 'var(--button-secondary-disabled-stroke)',
          'disabled-text': 'var(--button-secondary-disabled-text)',
        }
      },
      text: {
        primary: 'var(--text-primary)',
        'primary-inverted': 'var(--text-primary-inverted)',
        secondary: 'var(--text-secondary)',
        subtle: 'var(--text-subtle)',
        disabled: 'var(--text-disabled)',
        success: 'var(--text-success)',
        error: 'var(--text-error)',
        warning: 'var(--text-warning)',
        info: 'var(--text-info)',
        brand: 'var(--text-brand)',
        'info-bolder': 'var(--text-info-bolder)',
        'success-bolder': 'var(--text-success-bolder)',
        'error-bolder': 'var(--text-error-bolder)',
        'warning-bolder': 'var(--text-warning-bolder)',
        'brand-bolder': 'var(--text-brand-bolder)',
      },
      surface: {
        'default': 'var(--surface-default)',
        'default-hover': 'var(--surface-default-hover)',
        'low-emphasis': 'var(--surface-low-emphasis)',
        'medium-emphasis': 'var(--surface-medium-emphasis)',
        'high-emphasis': 'var(--surface-high-emphasis)',
        'skeleton': 'var(--surface-skeleton)',
        'default-error': 'var(--surface-default-error)',
        'default-primary': 'var(--surface-default-primary)',
        'default-success': 'var(--surface-default-success)',
        'default-warning': 'var(--surface-default-warning)',
        'accent-blue': 'var(--surface-accent-blue)',
        sidebar: {
          'item-default': 'var(--sidebar-item-default)',
          'item-active': 'var(--sidebar-item-active)',
          'icon-default': 'var(--sidebar-icon-default)',
          'icon-active': 'var(--sidebar-icon-active)',
          'tooltip': 'var(--sidebar-tooltip)',
        }
      },
      stroke: {
        'default': 'var(--stroke-default)',
        'subtle': 'var(--stroke-subtle)',
        'divider': 'var(--stroke-divider)',
        'medium': 'var(--stroke-medium)',
        'select': 'var(--stroke-select)',
        'strong': 'var(--stroke-strong)',
        'primary': 'var(--stroke-primary)',
        'error': 'var(--stroke-error)',
        'accent-success': 'var(--stroke-accent-success)',
      },
      icon: {
        'default': 'var(--icon-default)',
        'brand': 'var(--icon-brand)',
        'subtle': 'var(--icon-subtle)',
        'disabled': 'var(--icon-disabled)',
        'success': 'var(--icon-success)',
        'warning': 'var(--icon-warning)',
        'error': 'var(--icon-error)',
      },
      modal: {
        'surface-default': 'var(--modal-surface-default)',
        'surface-hover': 'var(--modal-surface-hover)',
      },
      color: {
        'blue-200': 'var(--blue-200)',
      },
      overlay: {
        'default': 'var(--overlay-default)',
      },
    },
    fontFamily: {
      sans: ["Geist", "sans-serif"],
      garamond: ["EB Garamond", "serif"],
    },
    fontSize: {
      xs: ["10px", "14px"],
      sm: ["12px", "16px"],
      base: ["14px", "21px"],
      md: ["15px", "21px"],
      lg: ["18px", "25px"],
      xl: ["24px", "33px"],
      "2xl": ["36px", "49px"],
    },
    fontWeight: {
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    extend: {
      boxShadow: {
        right: "2px 0px 6px 0px #0000000A",
        left: "-2px 0px 6px 0px #0000000A",
        1: "0px 2px 10px rgba(0, 0, 0, 0.1)",
        2: "0px 2px 5px 0px rgba(0,0,0,0.06)",
        modal: 'var(--modal-shadow)',
        panel: "0px 4px 8px 0px rgba(0,0,0,0.04)",
      },
      opacity: {
        '16': '0.16',
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '24px',
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        '.scrollbar-hide': {
          scrollbarWidth: 'none', /* Firefox */
          '&::-webkit-scrollbar': {
            display: 'none', /* Chrome, Safari, Opera*/
          },
        },
        '.scrollbar-thin': {
          '&::-webkit-scrollbar': {
            width: '6px',
            height: '6px',
          },
          '&::-webkit-scrollbar-track': {
            'background-color': 'transparent',
          },
          '&::-webkit-scrollbar-thumb': {
            'background-color': 'var(--surface-high-emphasis)',
            'border-radius': '9999px',
          },
          '&:hover::-webkit-scrollbar-thumb': {
            'background-color': 'var(--surface-medium-emphasis)',
          },
        },
        '.scrollbar-extra-thin': {
          '&::-webkit-scrollbar': {
            width: '4px',
          },
          '&::-webkit-scrollbar-track': {
            'background-color': 'transparent',
          },
          '&::-webkit-scrollbar-thumb': {
            'background-color': 'var(--surface-high-emphasis)',
            'border-radius': '9999px',
          },
          '&:hover::-webkit-scrollbar-thumb': {
            'background-color': 'var(--surface-medium-emphasis)',
          },
        }
      };
      addUtilities(newUtilities, ['responsive', 'hover']);
    },
  ],
};